print('LINHA 01')
print('LINHA 02')
# FALANDO DO QUE SE TRATA ESSA LINHA
print('LINHA 03')
print('LINHA 04')  # ISSO É UM COMENTÁRIO
print('LINHA 05')
print('LINHA 06')

# COMENTÁRIO MULTILINHA

"""
print('LINHA 01')
print('LINHA 02')
# FALANDO DO QUE SE TRATA ESSA LINHA
print('LINHA 03')
print('LINHA 04')  # ISSO É UM COMENTÁRIO
print('LINHA 05')
print('LINHA 06')
"""